apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-golang-http-2-yt3t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-golang-http-2-yt3t
    app.kubernetes.io/part-of: my-app-1
  name: sample-golang-http-2-yt3t
  namespace: flacatus-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sample-golang-http-2-yt3t
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sample-golang-http-2-yt3t
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:146e8d0c8e026269f8f6f51f04269e7df9956383b9900062a6fbfd0e06206b60
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
