apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-golang-http-2-yt3t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-golang-http-2-yt3t
    app.kubernetes.io/part-of: my-app-1
  name: sample-golang-http-2-yt3t
  namespace: flacatus-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: sample-golang-http-2-yt3t
status:
  loadBalancer: {}
